---
title: Solución de la ecuación del calor en un rectángulo
fontsize: 11pt
lang: es-AR
number-sections: true
geometry:
- paper=a4paper
- left=2.5cm
- right=2cm
- bottom=3.5cm
- foot=2cm
- top=3.5cm
- head=2cm
colorlinks: true
mathspec: true
toc: false
...
